apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Values.certificate.namespace }}
spec:
  secretName: {{ .Values.certificate.secretName }}
  commonName: {{ .Values.certificate.domainName }}
  issuerRef:
    kind: {{ .Values.certificate.issuerKind }}
    name: {{ .Values.certificate.issuerName }}
  dnsNames:
  - {{ .Values.certificate.domainName }}