---
apiVersion: v1
kind: Service
metadata:
  name: weather-service
  namespace: opentelemetry-example
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.deployment.httpPortWeatherService }}
    targetPort: {{ .Values.deployment.httpPortWeatherService }}
  selector:
    app: opentelemetry-example
---
apiVersion: v1
kind: Service
metadata:
  name: weather-adapter-service
  namespace: opentelemetry-example
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.deployment.httpPortWeatherAdapterService }}
    targetPort: {{ .Values.deployment.httpPortWeatherAdapterService }}
  selector:
    app: opentelemetry-example
---